apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "~~{NAME}~~-config-exep"
  namespace: "~~{KUBERNET_NAMESPACE}~~"
  labels:
    app: "~~{NAME}~~"
data:
  TRUSTED_PROXY: "~~{TRUSTED_PROXY}~~"
  DNS_SERVER: "~~{DNS_SERVER}~~"
  MAIL_SERVER: "~~{MAIL_FORWARD_HOST}~~"
  DATA_SERVER: "~~{DATA_SERVER}~~"
  DOCUMENT_ROOT: "~{web}{DOCUMENT_ROOT}~"
  WEB_DATA_ROOT: "~{web}{DATA_ROOT}~"
  SITE_NAME: "~{web}{SITE_NAME}~"
  SITE_ALIAS: "~{web}{SITE_ALIAS}~"
  SITE_LOG_LEVEL: "~{web}{WEB_LOG_LEVEL}~"
  APP_ENVIRONMENT: "~{web}{APP_ENVIRONMENT}~"
  CONFIG_TYPE: "~{web}{WEB_CONFIG_TYPE}~"
  LISTEN_PORT: "~{web}{WEB_LISTEN_PORT}~"
  WEB_DATA_MOUNTS: "~{web}{WEB_DATA_MOUNTS}~"
  APP_DATA_ROOT: "~{app}{DATA_ROOT}~"
  APP_CONFIG_ROOT: "~{app}{CONF_ROOT}~"
  APP_LISTEN_PORT: "~{app}{APP_LISTEN_PORT}~"
  APP_URL: "127.0.0.1:~{app}{APP_LISTEN_PORT}~"
  APP_DATA_MOUNTS: "~{app}{APP_DATA_MOUNTS}~"
  APP_CONFIG_MOUNTS: "~{app}{APP_CONFIG_MOUNTS}~"
  DATA_SOURCE_PATH: "/home/~~{KUBERNET_NAMESPACE}~~/source/~~{SERVER_NAME}~~"
  DATA_FILES_PATH: "/home/~~{KUBERNET_NAMESPACE}~~/data/~~{SERVER_NAME}~~"
  DATA_SETTINGS_PATH: "/home/~~{KUBERNET_NAMESPACE}~~/conf/~~{SERVER_NAME}~~"
