#!/bin/bash

set -e

if [[ -n "${VERSION}" ]]; then
    docker_inspect "${PREFIX}${NAME}-${VERSION}" >/dev/null 2>&1 || build_image
    docker push "${PREFIX}${NAME}-${VERSION}"
fi

docker push "${PREFIX}${NAME}"
