#!/bin/bash

postconf -e "inet_interfaces = ${INTERFACES:-all}"
postconf -e "maillog_file = ${MAIL_LOG:-/dev/stdout}"

if [[ -n "${PROTOCOLS}" ]]; then
  postconf -e "inet_protocols = ${PROTOCOLS}"
fi

if [[ -n "${HOST}" ]]; then
  postconf -e "myhostname = ${HOST}"
fi

if [[ -n "${DESTINATION}" ]]; then
  postconf -e "mydestination = ${DESTINATION}"
fi

if [[ -n "${BANNER}" ]]; then
  postconf -e "smtpd_banner = ${BANNER}"
fi

if [[ -n "${RELAY_DOMAINS}" ]]; then
  postconf -e "relay_domains = ${RELAY_DOMAINS}"
fi

if [[ (-n "${RELAY}") && (-n "${PORT}") ]]; then
    postconf -e 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
    postconf -e "relayhost = [${RELAY}]:${PORT}"
    postconf -e 'mynetworks = 127.0.0.0/8 172.16.0.0/12 172.17.0.0/16 10.0.0.0/8'
    if [[ (-n "${USER}") && (-n "${PASSWORD}") ]]; then
            postconf -e 'smtp_sasl_auth_enable = yes'
            postconf -e 'smtp_sasl_password_maps = hash:/etc/postfix/relay_password'
            postconf -e 'smtp_sasl_security_options = noanonymous'
            postconf -e 'smtp_tls_security_level = encrypt'
            echo "${RELAY}   ${USER}:${PASSWORD}" > /etc/postfix/relay_password
            postmap /etc/postfix/relay_password
    fi
else
    postconf -e 'mynetworks = 127.0.0.1/32 192.168.0.0/16 172.16.0.0/12 172.17.0.0/16 10.0.0.0/8'
fi

if [[ "$(grep -c "^#header_checks" /etc/postfix/main.cf)" -eq 1 ]]; then
	sed -i 's/#header_checks/header_checks/' /etc/postfix/main.cf
        echo "/^Subject:/     WARN" >> /etc/postfix/header_checks
        postmap /etc/postfix/header_checks
fi

for file in resolv.conf hosts host.conf localtime nsswitch.conf services
do
  ln -snf "/etc/$file" "/var/spool/postfix/etc/$file"
done
