#!/bin/bash

postconf -e "inet_interfaces = ${INTERFACES:-all}"
postconf -e "maillog_file = ${MAIL_LOG:-/dev/stdout}"

if [[ -n "${PROTOCOLS}" ]]; then
  postconf -e "inet_protocols = ${PROTOCOLS}"
fi

if [[ -n "${HOST_NAME}" ]]; then
  postconf -e "myhostname = ${HOST_NAME}"
fi

if [[ -n "${DESTINATION}" ]]; then
  postconf -e "mydestination = ${DESTINATION}"
fi

if [[ -n "${BANNER}" ]]; then
  postconf -e "smtpd_banner = ${BANNER}"
fi

if [[ -n "${RELAY_DOMAINS}" ]]; then
  postconf -e "relay_domains = ${RELAY_DOMAINS}"
fi

if [[ (-n "${RELAY}") && (-n "${PORT}") ]]; then
  postconf -e 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
  mkdir -p /var/spool/postfix/etc/ssl/certs
  cp /etc/ssl/certs/ca-certificates.crt /var/spool/postfix/etc/ssl/certs/ca-certificates.crt
  postconf -e "relayhost = [${RELAY}]:${PORT}"
  if [[ (-n "${USER}") && (-n "${PASSWORD}") ]]; then
    postconf -e 'smtp_sasl_auth_enable = yes'
    postconf -e 'smtp_sasl_password_maps = hash:/etc/postfix/relay_password'
    postconf -e 'smtp_sasl_security_options = noanonymous'
    postconf -e 'smtp_tls_security_level = encrypt'
    echo "${RELAY}   ${USER}:${PASSWORD}" > /etc/postfix/relay_password
    postmap /etc/postfix/relay_password
  fi
fi

postconf -e 'mynetworks = 127.0.0.1/32 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8'
if [[ (-n "${KEY_FILE}") && (-n "${CERT_FILE}") ]];then
  postconf -e "smtpd_use_tls = yes"
  postconf -e 'smtp_tls_security_level = may'
  postconf -e "smtpd_tls_key_file = /etc/postfix/certs/${KEY_FILE}"
  postconf -e "smtpd_tls_cert_file = /etc/postfix/certs/${CERT_FILE}"
  mkdir -p "$(dirname "/var/spool/postfix/etc/postfix/certs/${KEY_FILE}")"
  mkdir -p "$(dirname "/var/spool/postfix/etc/postfix/certs/${CERT_FILE}")"
  cp "/etc/postfix/certs/${KEY_FILE}" "/var/spool/postfix/etc/postfix/certs/${KEY_FILE}"
  cp "/etc/postfix/certs/${CERT_FILE}" "/var/spool/postfix/etc/postfix/certs/${CERT_FILE}"
fi


if [[ "$(grep -c "^#header_checks" /etc/postfix/main.cf)" -eq 1 ]]; then
	sed -i 's/#header_checks/header_checks/' /etc/postfix/main.cf
        echo "/^Subject:/     WARN" >> /etc/postfix/header_checks
        postmap /etc/postfix/header_checks
fi

# Debian runs postfix is chrooted env.
for file in resolv.conf hosts host.conf localtime nsswitch.conf services
do
  cp "/etc/$file" "/var/spool/postfix/etc/$file"
done
